import { useEffect, useState } from 'react';
import { Edit3, Image, PackagePlus, Plus, Trash2, X } from 'lucide-react';
import { COLORS, FONT_IMPORT, PageHeader, PrimaryButton } from './Theme';

type Garment = { id?: number; name: string; price: string; description: string; fabrics: string[]; image: string; colors: string[] };

const DEFAULT_CATALOG: Garment[] = [
  { name: 'Barong Tagalog', price: 'From ₱6,500', description: 'Hand-finished formal wear for weddings and ceremonies.', fabrics: ['Piña Jusi — Ivory', 'Cocoon Silk — Natural'], colors: ['#F5EEDF', '#D8C9A7'], image: 'https://ibarrafilipino.com/cdn/shop/files/Barong_Tagalog_JV402_02.png?v=1769481827&width=1200' },
  { name: 'Two-piece Suit', price: 'From ₱12,000', description: 'A tailored jacket and trousers, cut to your measurements.', fabrics: ['Italian Wool — Charcoal', 'Wool Blend — Navy'], colors: ['#393B42', '#1D2A44'], image: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200' },
  { name: 'Filipiniana Dress', price: 'From ₱9,500', description: 'Custom occasion dress with a silhouette made for you.', fabrics: ['Silk Habotai — Wine', 'Satin — Blush'], colors: ['#6A2737', '#D9A6A6'], image: 'https://www.kulturafilipino.com/cdn/shop/files/Copyof_IMG8614_1800x1800.jpg?v=1722242874' },
  { name: 'School Uniform Set', price: 'From ₱2,800', description: 'Durable uniforms tailored for everyday wear.', fabrics: ['Cotton Twill — Navy', 'Cotton Poplin — White'], colors: ['#233553', '#ECE9E0'], image: 'https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=1200' },
];

const emptyGarment: Garment = { name: '', price: '', description: '', fabrics: [], image: '', colors: ['#E6DED1', '#B58A3A'] };
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const authToken = () => localStorage.getItem('authToken') || sessionStorage.getItem('authToken') || '';

export function AdminGarmentCatalogView() {
  const [catalog, setCatalog] = useState<Garment[]>(DEFAULT_CATALOG);
  const [editing, setEditing] = useState<Garment | null>(null);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { fetch(`${API_URL}/auth/catalog`, { headers: { Authorization: `Bearer ${authToken()}` } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setCatalog(data.catalog); }).catch((requestError) => { setError(requestError instanceof Error ? requestError.message : 'Unable to load the catalog.'); }); }, []);
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3500); };
  const remove = async (garment: Garment) => { if (!window.confirm(`Remove ${garment.name} from the customer catalog?`)) return; try { const response = await fetch(`${API_URL}/auth/catalog/${garment.id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${authToken()}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setCatalog((current) => current.filter((item) => item.id !== garment.id)); flash(`${garment.name} was removed from the catalog.`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to remove garment.'); } };
  const save = async (garment: Garment) => { try { const editId = editing?.id; const isEdit = Boolean(editId); const response = await fetch(`${API_URL}/auth/catalog${editId ? `/${editId}` : ''}`, { method: isEdit ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${authToken()}` }, body: JSON.stringify(garment) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setCatalog((current) => isEdit ? current.map((item) => item.id === data.garment.id ? data.garment : item) : [...current, data.garment]); setEditing(null); flash(`${data.garment.name} was ${isEdit ? 'updated' : 'added'} to the catalog.`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save garment.'); } };

  return <div className="space-y-7" style={{ color: COLORS.ink }}><style>{FONT_IMPORT}</style>
    <PageHeader eyebrow="Customer storefront" title="Garment Catalog" description="Manage the garments customers can browse and request online." action={<PrimaryButton icon={<PackagePlus />} onClick={() => setEditing(emptyGarment)}>Add garment</PrimaryButton>} />
    {notice && <div className="border px-4 py-3 text-sm" style={{ borderColor: COLORS.successBorder, background: COLORS.successBg, color: COLORS.success, borderRadius: 8 }}>{notice}</div>}{error && <div className="border px-4 py-3 text-sm" style={{ borderColor: COLORS.dangerBorder, background: COLORS.dangerBg, color: COLORS.danger, borderRadius: 8 }}>{error}</div>}
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{catalog.map((garment) => <article key={garment.id || garment.name} className="overflow-hidden border bg-white" style={{ borderColor: COLORS.border, borderRadius: 10 }}><img src={garment.image} alt={garment.name} className="h-44 w-full object-cover" /><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold">{garment.name}</h2><p className="mt-1 text-sm font-semibold" style={{ color: COLORS.brassDeep }}>{garment.price}</p></div><Image className="h-4 w-4" style={{ color: COLORS.faint }} /></div><p className="mt-3 min-h-10 text-sm" style={{ color: COLORS.muted }}>{garment.description}</p><p className="mt-3 text-xs" style={{ color: COLORS.inkSoft }}>{garment.fabrics.join(' · ')}</p><div className="mt-5 flex gap-2"><button onClick={() => setEditing(garment)} className="inline-flex items-center gap-1.5 border px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.1em]" style={{ borderColor: COLORS.border, borderRadius: 7, color: COLORS.inkSoft }}><Edit3 className="h-3.5 w-3.5" />Edit</button><button onClick={() => remove(garment)} className="inline-flex items-center gap-1.5 border px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.1em]" style={{ borderColor: '#F0C9C3', borderRadius: 7, color: COLORS.danger }}><Trash2 className="h-3.5 w-3.5" />Remove</button></div></div></article>)}</div>
    {editing && <GarmentForm garment={editing} onClose={() => setEditing(null)} onSave={save} />}
  </div>;
}

function GarmentForm({ garment, onClose, onSave }: { garment: Garment; onClose: () => void; onSave: (garment: Garment) => void }) {
  const [form, setForm] = useState({ ...garment, fabrics: garment.fabrics.join(', ') });
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button onClick={onClose} className="absolute inset-0 bg-black/45 backdrop-blur-sm" aria-label="Close garment form" /><form onSubmit={(event) => { event.preventDefault(); onSave({ ...form, fabrics: form.fabrics.split(',').map((item) => item.trim()).filter(Boolean), colors: form.colors }); }} className="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto border bg-white p-7 shadow-2xl" style={{ borderColor: COLORS.border, borderRadius: 12 }}><button type="button" onClick={onClose} className="absolute right-5 top-5" style={{ color: COLORS.muted }}><X className="h-5 w-5" /></button><span className="text-[10px] font-semibold uppercase tracking-[0.12em]" style={{ color: COLORS.brassDeep }}>Customer storefront</span><h2 className="mt-1 text-2xl font-semibold">{garment.name ? 'Edit garment' : 'Add garment'}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Garment name" value={form.name} onChange={(value) => update('name', value)} required /><Input label="Starting price" value={form.price} onChange={(value) => update('price', value)} placeholder="From ₱5,000" required /><div className="sm:col-span-2"><Input label="Image URL" value={form.image} onChange={(value) => update('image', value)} placeholder="https://..." required /></div><div className="sm:col-span-2"><label className="block text-xs font-semibold" style={{ color: COLORS.inkSoft }}>Description<textarea required value={form.description} onChange={(event) => update('description', event.target.value)} rows={3} className="mt-2 w-full border px-3 py-2.5 text-sm outline-none" style={{ borderColor: COLORS.border, borderRadius: 8 }} /></label></div><div className="sm:col-span-2"><Input label="Available fabrics (separate with commas)" value={form.fabrics} onChange={(value) => update('fabrics', value)} placeholder="Piña Jusi — Ivory, Cocoon Silk — Natural" /></div></div><div className="mt-7 flex gap-3"><PrimaryButton icon={<Plus />}>{garment.name ? 'Save changes' : 'Add garment'}</PrimaryButton><button type="button" onClick={onClose} className="border px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[0.1em]" style={{ borderColor: COLORS.border, borderRadius: 8, color: COLORS.muted }}>Cancel</button></div></form></div>;
}

function Input({ label, value, onChange, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean }) { return <label className="block text-xs font-semibold" style={{ color: COLORS.inkSoft }}>{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full border px-3 py-2.5 text-sm outline-none" style={{ borderColor: COLORS.border, borderRadius: 8 }} /></label>; }

export default AdminGarmentCatalogView;
