import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, ClipboardList, PackageCheck, Search, Shirt, X } from 'lucide-react';

type Order = { id: string; customer: string; garment: string; fabric: string; stage: string; payment: 'Deposit paid' | 'Paid' | 'Balance due'; total: string; due: string; created: string; measurements: string; };

const ORDERS: Order[] = [
  { id: 'JC-3021', customer: 'Reyna Fuentes', garment: 'Barong Tagalog', fabric: 'Piña Jusi — Ivory', stage: 'First Fitting', payment: 'Deposit paid', total: '₱4,800', due: 'Aug 05', created: 'Jul 27, 2026', measurements: 'CUS-001 measurement profile' },
  { id: 'JC-3020', customer: 'Boyet Salcedo', garment: 'Two-piece Suit', fabric: 'Italian Wool — Charcoal', stage: 'Pattern Cutting', payment: 'Deposit paid', total: '₱12,500', due: 'Aug 09', created: 'Jul 26, 2026', measurements: 'CUS-002 measurement profile' },
  { id: 'JC-3019', customer: 'Consuelo Reyes', garment: "Women's Coat", fabric: 'Wool Blend — Camel', stage: 'Final Alterations', payment: 'Paid', total: '₱7,200', due: 'Aug 03', created: 'Jul 24, 2026', measurements: 'CUS-003 measurement profile' },
  { id: 'JC-3018', customer: 'Tomas Villareal', garment: 'School Uniform Set', fabric: 'Polyester — Navy', stage: 'Ready for Pickup', payment: 'Balance due', total: '₱2,150', due: 'Aug 02', created: 'Jul 23, 2026', measurements: 'CUS-004 measurement profile' },
  { id: 'JC-3017', customer: 'Marisol Chan', garment: 'Evening Gown', fabric: 'Silk Habotai — Wine', stage: 'Initial Assembly', payment: 'Deposit paid', total: '₱15,900', due: 'Aug 12', created: 'Jul 21, 2026', measurements: 'CUS-005 measurement profile' },
  { id: 'JC-3016', customer: 'Cesar de la Cruz', garment: 'Long-sleeve Polo', fabric: 'Cotton Poplin — White', stage: 'Completed', payment: 'Paid', total: '₱2,850', due: 'Jul 31', created: 'Jul 18, 2026', measurements: 'CUS-006 measurement profile' },
];

const stageClasses: Record<string, string> = { 'Pattern Cutting': 'bg-[#E4EEEE] text-[#2C4A57] border-[#B9D8DD]', 'Initial Assembly': 'bg-[#F1ECFA] text-[#69528C] border-[#D5C8E8]', 'First Fitting': 'bg-[#FFF3DD] text-[#8A6618] border-[#ECD8A7]', 'Final Alterations': 'bg-[#FCEAE7] text-[#9B4D45] border-[#EDC7C1]', Completed: 'bg-[#E7F4EE] text-[#277257] border-[#B9DDD0]', 'Ready for Pickup': 'bg-[#E2F3F4] text-[#1E6E78] border-[#A9DADD]' };

export function AdminOrdersView({ externalQuery = '' }: { externalQuery?: string }) {
  const [query, setQuery] = useState(externalQuery);
  const [filter, setFilter] = useState('All stages');
  const [selected, setSelected] = useState<Order | null>(null);
  useEffect(() => setQuery(externalQuery), [externalQuery]);
  const stages = ['All stages', ...Array.from(new Set(ORDERS.map((order) => order.stage)))];
  const orders = useMemo(() => ORDERS.filter((order) => `${order.id} ${order.customer} ${order.garment}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All stages' || order.stage === filter)), [query, filter]);
  const total = ORDERS.reduce((sum, order) => sum + Number(order.total.replace(/[^0-9]/g, '')), 0);

  return <div className="space-y-7">
    <div className="dash-in flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[10px] uppercase tracking-[0.22em] text-[#5D7480]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>Custom order management</span><h1 className="mt-1 text-2xl sm:text-3xl text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>Orders</h1><p className="mt-2 text-sm text-[#5D7480]">Monitor job cards, deadlines, production progress, and payments.</p></div><div className="border border-[#C7D2CE] bg-[#F7FAF9] px-4 py-3"><span className="text-xl text-[#122029]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>₱{total.toLocaleString()}</span><span className="ml-2 text-[10px] uppercase tracking-[0.15em] text-[#5D7480]">Order value</span></div></div>
    <div className="dash-in grid grid-cols-2 gap-4 lg:grid-cols-4" style={{ animationDelay: '0.08s' }}><Summary icon={<ClipboardList />} label="Open orders" value={5} /><Summary icon={<CalendarDays />} label="Due this week" value={3} /><Summary icon={<PackageCheck />} label="Ready for pickup" value={1} /><Summary icon={<Shirt />} label="Completed this month" value={12} /></div>
    <section className="dash-in border border-[#C7D2CE] bg-[#F7FAF9] shadow-[0_1px_3px_rgba(18,32,41,0.06)]" style={{ animationDelay: '0.14s' }}><div className="flex flex-col gap-4 border-b border-[#C7D2CE] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8FA2A8]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search job card, customer, or garment" className="w-full border border-[#C7D2CE] bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-[#4FB6C4]" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)} className="border border-[#C7D2CE] bg-white px-3 py-2.5 text-sm text-[#3D4F55] outline-none focus:border-[#4FB6C4]">{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></div><div className="hidden grid-cols-[0.8fr_1.2fr_1.2fr_1.15fr_0.9fr_0.75fr_24px] gap-4 border-b border-[#C7D2CE] bg-[#EDF1F0] px-6 py-3 md:grid">{['Job card', 'Customer', 'Garment', 'Production stage', 'Payment', 'Due', ''].map((label) => <span key={label} className="text-[10px] uppercase tracking-[0.16em] text-[#5D7480]">{label}</span>)}</div>{orders.map((order) => <button key={order.id} onClick={() => setSelected(order)} className="grid w-full grid-cols-1 gap-2 border-b border-[#DEE5DF] px-6 py-4 text-left transition-colors hover:bg-[#EDF5F3] md:grid-cols-[0.8fr_1.2fr_1.2fr_1.15fr_0.9fr_0.75fr_24px] md:items-center md:gap-4"><span className="text-[12px] text-[#2C4A57]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>{order.id}</span><span className="font-medium text-[#122029]">{order.customer}</span><span className="text-sm text-[#3D4F55]">{order.garment}</span><span><span className={`inline-block border px-2 py-1 text-[10px] uppercase tracking-[0.08em] ${stageClasses[order.stage]}`}>{order.stage}</span></span><span className={`text-sm ${order.payment === 'Balance due' ? 'text-[#9B4D45]' : 'text-[#3F7D5C]'}`}>{order.payment}</span><span className="text-sm text-[#3D4F55]">{order.due}</span><ChevronRight className="hidden h-4 w-4 text-[#4FB6C4] md:block" /></button>)}{!orders.length && <div className="p-12 text-center text-sm text-[#5D7480]">No order matches your search.</div>}</section>{selected && <OrderDetails order={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="border border-[#C7D2CE] bg-[#F7FAF9] p-5"><div className="flex items-center justify-between text-[#2C4A57]"><div className="flex h-8 w-8 items-center justify-center bg-[#4FB6C4]/15 [&>svg]:h-4 [&>svg]:w-4">{icon}</div><span className="text-2xl text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>{value}</span></div><div className="mt-4 text-[10px] uppercase tracking-[0.16em] text-[#5D7480]">{label}</div></div>; }

function OrderDetails({ order, onClose }: { order: Order; onClose: () => void }) { const steps = ['Measuring', 'Pattern Cutting', 'Initial Assembly', 'First Fitting', 'Final Alterations', 'Completed', 'Ready for Pickup']; const active = steps.indexOf(order.stage); return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Close order details" onClick={onClose} className="absolute inset-0 bg-[#0E1E2A]/50 backdrop-blur-sm" /><section className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto border border-[#C7D2CE] bg-[#F7FAF9] shadow-2xl"><header className="flex items-start justify-between border-b border-[#C7D2CE] px-6 py-6 sm:px-8"><div><span className="text-[10px] uppercase tracking-[0.22em] text-[#5D7480]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>Job card details</span><h2 className="mt-1 text-3xl text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>{order.id}</h2><p className="mt-1 text-sm text-[#5D7480]">{order.customer} · {order.garment}</p></div><button onClick={onClose} className="p-2 text-[#5D7480] hover:bg-[#E4EEEE]"><X className="h-5 w-5" /></button></header><div className="space-y-8 p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2">{[['Customer', order.customer], ['Garment', order.garment], ['Fabric', order.fabric], ['Measurement profile', order.measurements], ['Created', order.created], ['Due date', order.due], ['Total', order.total], ['Payment', order.payment]].map(([label, value]) => <div key={label} className="border border-[#C7D2CE] bg-white p-4"><div className="text-[10px] uppercase tracking-[0.14em] text-[#5D7480]">{label}</div><div className="mt-1 text-sm text-[#122029]">{value}</div></div>)}</div><div><h3 className="text-lg text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>Production timeline</h3><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{steps.map((step, index) => <div key={step} className={`border p-3 ${index <= active ? 'border-[#4FB6C4] bg-[#E4EEEE]' : 'border-[#C7D2CE] bg-white'}`}><div className="text-[10px] text-[#5D7480]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>{String(index + 1).padStart(2, '0')}</div><div className="mt-1 text-xs text-[#122029]">{step}</div></div>)}</div></div></div></section></div>; }

export default AdminOrdersView;
