import { useState } from 'react';
import { Bell, Building2, Check, LockKeyhole, Save, SlidersHorizontal } from 'lucide-react';

export function AdminSettingsWideView() {
  const [saved, setSaved] = useState(false);
  const [settings, setSettings] = useState({ name: "Ashlie's Tailor", email: 'hello@ashliestailor.com', phone: '0917 555 0100', address: 'Tagbilaran City, Bohol', deposit: '50', lowStock: true, fitting: true, pickup: true });
  const update = (key: keyof typeof settings, value: string | boolean) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 3000); };
  return <div className="w-full space-y-7"><div><span className="text-[10px] uppercase tracking-[0.22em] text-[#5D7480]" style={{ fontFamily: "'IBM Plex Mono', monospace" }}>System configuration</span><h1 className="mt-1 text-2xl sm:text-3xl text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>Settings</h1><p className="mt-2 text-sm text-[#5D7480]">Manage shop information, order rules, and notification preferences.</p></div>{saved && <div className="flex items-center gap-2 border border-[#B9DDD0] bg-[#E7F4EE] px-4 py-3 text-sm text-[#277257]"><Check className="h-4 w-4" /> Settings saved successfully.</div>}<Card icon={<Building2 />} title="Shop information" description="Details shown on receipts and customer communications."><div className="grid gap-5 sm:grid-cols-2"><Field label="Shop name" value={settings.name} onChange={(value) => update('name', value)} /><Field label="Shop email" type="email" value={settings.email} onChange={(value) => update('email', value)} /><Field label="Contact number" value={settings.phone} onChange={(value) => update('phone', value)} /><div className="sm:col-span-2"><Field label="Shop address" value={settings.address} onChange={(value) => update('address', value)} /></div></div></Card><Card icon={<SlidersHorizontal />} title="Order rules" description="Default rules used while creating a custom order."><div className="max-w-md"><Field label="Required deposit (%)" type="number" value={settings.deposit} onChange={(value) => update('deposit', value)} /></div></Card><Card icon={<Bell />} title="Notifications" description="Choose which shop events require an alert."><div className="divide-y divide-[#DEE5DF] border-y border-[#DEE5DF]"><Toggle label="Low-stock alerts" detail="Notify when fabric reaches its reorder level." checked={settings.lowStock} onChange={(value) => update('lowStock', value)} /><Toggle label="Fitting reminders" detail="Notify staff about upcoming fitting appointments." checked={settings.fitting} onChange={(value) => update('fitting', value)} /><Toggle label="Pickup reminders" detail="Notify staff when completed garments are ready for pickup." checked={settings.pickup} onChange={(value) => update('pickup', value)} /></div></Card><Card icon={<LockKeyhole />} title="Security" description="Manage account access under User Management."><button className="border border-[#C7D2CE] bg-white px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#3D4F55]">Change admin password</button></Card><button onClick={save} className="inline-flex items-center gap-2 bg-[#2C4A57] px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.15em] text-white"><Save className="h-4 w-4" /> Save settings</button></div>;
}
function Card({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="border border-[#C7D2CE] bg-[#F7FAF9] p-6 sm:p-8"><div className="flex items-center gap-3"><span className="text-[#4FB6C4] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><h2 className="text-lg text-[#122029]" style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600 }}>{title}</h2><p className="mt-1 text-sm text-[#5D7480]">{description}</p></div></div><div className="mt-6">{children}</div></section>; }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="block text-xs font-medium text-[#3D4F55]">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full border border-[#C7D2CE] bg-white px-3 py-2.5 text-sm text-[#122029] outline-none focus:border-[#4FB6C4]" /></label>; }
function Toggle({ label, detail, checked, onChange }: { label: string; detail: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-6 py-4"><span><span className="block text-sm font-medium text-[#122029]">{label}</span><span className="mt-1 block text-xs text-[#5D7480]">{detail}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-[#2C4A57]" /></label>; }
export default AdminSettingsWideView;
